### ISSUE TITLE
Rebirth...

### ISSUE THREAD

**Issue by sletz** [aonurdemir/Mephisto#2]
Nice to see a rebirth of this project ! We added it there: https://faust.grame.fr/community/powered-by-faust/#mephisto, it would be nice to add a screenshot or something. Do you have one?

**Comment by aonurdemir** [comment]
Thanks @sletz. I am happy to see that the project is listed on Faust's page. It felt great to me.

Also, I will be happy to see the projects which are made by using Mephisto. I will be tracking them as much as possible.

Mephisto does not have a UI but I can create a simple flowchart or something telling what Mephisto does.

**Comment by sletz** [comment]
Yes a simple flowchart or similar would be great! Thanks.

**Comment by aonurdemir** [comment]
Hello @sletz,

We can add the image below to showcase Mephisto. Thanks a lot.

![mephisto](https://user-images.githubusercontent.com/5756213/205006843-06fdf28f-724a-43fe-9d54-87e1a36f6dae.jpg)

**Comment by sletz** [comment]
Done here: https://faust.grame.fr/community/powered-by-faust/#mephisto thanks !
